### PR TITLE
[SYTO-859] Create anchor links for testing Mortar Components 

### PR DESCRIPTION
**Pull request by hkekeli**
https://jira.natgeo.com/browse/SYTO-859

Instructions: 

Checkout branch
Confirm the following links take you to the right components

http://localhost:3000/components/#slider
http://localhost:3000/components/#sharing
http://localhost:3000/components/#promo-card
http://localhost:3000/components/#video
http://localhost:3000/components/#video-playlist
http://localhost:3000/components/#tooltips
http://localhost:3000/components/#pod-promo
http://localhost:3000/components/#photo-gallery
http://localhost:3000/components/#icon
http://localhost:3000/components/#button
http://localhost:3000/components/#modals
http://localhost:3000/components/#photo-caption
http://localhost:3000/components/#ratios
http://localhost:3000/components/#related-content

For QA: http://assets-qa.int.ngeo.com/mortar3/latest/site/components/#slider
[...]

### CODE REVIEW

**Comment by pmourelle** [comment]
Links work fine.
The only "but" is the fixed top nav that covers title of section. Maybe setting some margin-top or something to add offset needed?

**Comment by hkekeli** [comment]
Setting a margin or padding creates more white space around the content than the design called for. If Kevin is fine with this approach I can implement. Anything else is probably outside the scope of this ticket.

**Comment by pmourelle** [comment]
@hkekeli no need to. You can set for those anchors:
```
padding-top: 40px;
margin-top: -40px;
```

**Comment by hkekeli** [comment]
@pmourelle It's ready

**Comment by pmourelle** [comment]
Looks great.
PR OK.

**Pull request merged**
