### PR TITLE
[AEM-3353] remove text-shadow: none from selection

### PR DESCRIPTION
**Pull request by bpearsoncse**
Change per Kevin's comments in: https://jira.nationalgeographic.com/browse/AEM-3353

### CODE REVIEW

**Comment by asabaylus** [comment]
Please double check with @DavidCoulter

**Comment by bpearsoncse** [comment]
@davidocoulter Not sure who/how you guys want to handle testing/deployment.

**Comment by davidocoulter** [comment]
@asabaylus, I am uninvolved with Mortar. That is @xiwcx's baby.

**Comment by bpearsoncse** [comment]
@xiwcx Please see previous comments.

**Comment by xiwcx** [comment]
@bpearsoncse, as long as someone on NGP staff (likely me, but occasionally it will be someone else) has done a peer review this can be considered tested. deployment can be handled by bumping the version in the bower package, committing code, and running `grunt deploy` (https://github.com/natgeo/mortar#grunt-deploy). I will update the documentation to make this more clear.

**Comment by bpearsoncse** [comment]
@xiwcx thanks. PR reassigned to you for review.

**Pull request merged**
