### PR TITLE
SYTO-771: Create the POD Promo Component

### PR DESCRIPTION
**Pull request by pgurley**
https://jira.natgeo.com/browse/SYTO-771

This story adds in the base POD component. Any styling will be handled in a subsequent story ([SYTO-753](https://jira.natgeo.com/browse/SYTO-753)), but there is some base styling in place simply to help verify component functionality

To test:

- Pull SYTO-771-mortar3
- Verify unit tests pass by running `npm test`
- Run `gulp serve`
- Verify component at http://localhost:3000/components/podpromo/index.html using the configurator
- Verify component also renders as expected at http://localhost:3000/components/

### CODE REVIEW

**Comment by benjachapman** [comment]
Very nicely done. All tests passing, linter passing, configurator page working quite well

This work introduces a pattern Phil and I discussed where the component will be equipped to retrieve its data through an endpoint, or directly in its markup. I think that provides a nice degree of flexibility. I reckon we ought to introduce a utility function so that Mortar components can retrieve data from endpoints in a single place, but for now this is sufficient.

**Comment by asabaylus** [comment]
@pgurley When I run npm test I get a bunch of unit test errors ex:
```
ERROR: 'Error on Module: PhotoGallery', '
 Instance Id:966f6b0a-0f22-67ba-31db-dd041e2fe5b0', '
 Message: null is not an object (evaluating 'this.options.frameAspectRatio')', '', '
```

**Comment by benjachapman** [comment]
I don't get any errors. @asabaylus are you running the tests in release/3.0? Is there something that points to this PR as causing the errors you're seeing?

**Comment by benjachapman** [comment]
pipeline passed all tests/linting after this merge as well: http://bamboo.int.ngeo.com/browse/MPPRJ-M3-MORT2UNT-11/log

**Comment by asabaylus** [comment]
@benjachapman Im seeing errors aplenty in both in the original branch and the release/v3.0 branch...

```

SUMMARY:
✔ 112 tests completed
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: Error on request (Ckeck json URL)
  at /var/folders/2d/2zg04cxj1k96v6fdf0jk3v_49mbxw0/T/8935221a419839f739f676b55f1310aa.browserify:3160 <- app/modules/videoplaylist/scripts/VideoPlaylistPestle.js:14:26

✖ Error while running the tests! Exit code: 1

[18:11:33] Finished 'karma' after 11 s
[18:11:33] Starting 'test'...
[18:11:33] Finished 'test' after 3.62 μs
[18:11:33] 'karma' errored after 11 s
[18:11:33] Error: 1
  at formatError (/Users/abaylus/Dropbox_NGS/Projects/mortar/node_modules/gulp/bin/gulp.js:169:10)
```

If you can confirm its not related to this story Ill go ahead and except. But I think there are potentially issues elsewhere and we'll have to create a ticket to deal with them.

**Comment by benjachapman** [comment]
@asabaylus I do see various "error" messages logged that correspond to your first comment - such as in the logs here for this merge's build: http://bamboo.int.ngeo.com/browse/MPPRJ-M3-MORT2UNT-11/log, but I'd cast doubt on how meaningful those errors are, given that the actual tests pass, and that similar "error" logs can be seen in the pipeline for Mortar 2 going back many months - for example, here's a successful Mortar 2 build in May: http://bamboo.int.ngeo.com/browse/MPPRJ-M2WBTOOLS-MORT2UNT-73/log

I'm unclear whether or not they indicate meaningful problems, but at any rate they have been long present in this code and were certainly not introduced within this PR.

**Comment by pgurley** [comment]
FWIW @asabaylus , I agree with @benjachapman that these errors that predate changes related to SYTO-771. PhotoGallery errors are showing up in a build from August 9. http://bamboo.int.ngeo.com/browse/MPPRJ-M3-MORT2UNT-5/log
```

09-Aug-2016 13:58:27	ERROR: 'Error on Module: PhotoGallery', '
09-Aug-2016 13:58:27	 Instance Id:f406fc0d-cb87-ad08-4d77-93c2d81db747', '
09-Aug-2016 13:58:27	 Message: null is not an object (evaluating 'this.options.frameAspectRatio')', '', '
09-Aug-2016 13:58:27	 Stack:', 'init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:669:39
09-Aug-2016 13:58:27	init@[native code]
09-Aug-2016 13:58:27	http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2458:17
09-Aug-2016 13:58:27	forEach@[native code]
09-Aug-2016 13:58:27	init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2447:44
09-Aug-2016 13:58:27	init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2134:30
09-Aug-2016 13:58:27	http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:67912:34
09-Aug-2016 13:58:27	callFn@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4471:25
09-Aug-2016 13:58:27	run@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4464:13
09-Aug-2016 13:58:27	next@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4810:13
09-Aug-2016 13:58:27	http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4832:9
09-Aug-2016 13:58:27	timeslice@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:75:27'
09-Aug-2016 13:58:27	  MTPhotoGallery
09-Aug-2016 13:58:27	    Pestle Module
09-Aug-2016 13:58:27	      ✔ should be a class
09-Aug-2016 13:58:27	      ✔ should be registered as a Pestle component
09-Aug-2016 13:58:27	      ✔ should mount
09-Aug-2016 13:58:27	    React Component
09-Aug-2016 13:58:27	      ✔ Should have a Heading component
09-Aug-2016 13:58:27	      ✔ Heading component has props
09-Aug-2016 13:58:27	      ✔ Should have a Counter component
09-Aug-2016 13:58:27	      ✔ Counter component should have props
09-Aug-2016 13:58:27	      ✔ Should have a Slider component
09-Aug-2016 13:58:27	      ✔ Slider component should have props
09-Aug-2016 13:58:27	      ✔ Should have a Captions component
09-Aug-2016 13:58:27	      ✔ Captions component should have slides prop
09-Aug-2016 13:58:27	ERROR: 'Error on Module: PhotoGallery', '
09-Aug-2016 13:58:27	 Instance Id:f406fc0d-cb87-ad08-4d77-93c2d81db747', '
09-Aug-2016 13:58:27	 Message: null is not an object (evaluating 'this.options.frameAspectRatio')', '', '
09-Aug-2016 13:58:27	 Stack:', 'init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:669:39
09-Aug-2016 13:58:27	init@[native code]
09-Aug-2016 13:58:27	http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2458:17
09-Aug-2016 13:58:27	forEach@[native code]
09-Aug-2016 13:58:27	init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2447:44
09-Aug-2016 13:58:27	init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2134:30
09-Aug-2016 13:58:27	http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:68059:34
09-Aug-2016 13:58:27	callFn@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4471:25
09-Aug-2016 13:58:27	run@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4464:13
09-Aug-2016 13:58:27	next@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4810:13
09-Aug-2016 13:58:27	http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4832:9
09-Aug-2016 13:58:27	timeslice@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:75:27'
09-Aug-2016 13:58:27	ERROR: 'Error on Module: PromoCard', '
09-Aug-2016 13:58:27	 Instance Id:7ab7a88d-9b9f-36ad-3172-9311e632b35d', '
09-Aug-2016 13:58:27	 Message: null is not an object (evaluating 'this.options.image')', '', '
09-Aug-2016 13:58:27	 Stack:', 'init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:1201:28
09-Aug-2016 13:58:27	init@[native code]
09-Aug-2016 13:58:27	http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2458:17
09-Aug-2016 13:58:27	forEach@[native code]
09-Aug-2016 13:58:27	init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2447:44
09-Aug-2016 13:58:27	init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2134:30
09-Aug-2016 13:58:27	http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:68059:34
09-Aug-2016 13:58:27	callFn@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4471:25
09-Aug-2016 13:58:27	run@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4464:13
09-Aug-2016 13:58:27	next@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4810:13
09-Aug-2016 13:58:27	http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4832:9
09-Aug-2016 13:58:27	timeslice@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:75:27'
09-Aug-2016 13:58:27	  MTPromoCard
09-Aug-2016 13:58:27	    Pestle Module
09-Aug-2016 13:58:27	      ✔ should be a class
09-Aug-2016 13:58:27	      ✔ should be registered as a Pestle component
09-Aug-2016 13:58:27	      ✔ should mount
09-Aug-2016 13:58:27	    React Component
09-Aug-2016 13:58:27	      ✔ Should have a containing div with classes
09-Aug-2016 13:58:27	      ✔ Should have a PromoImage component
09-Aug-2016 13:58:27	      ✔ PromoImage component should have props
09-Aug-2016 13:58:27	      ✔ Should have a PromoText component
09-Aug-2016 13:58:27	      ✔ PromoText component should have props
09-Aug-2016 13:58:27	ERROR: 'Error on Module: PhotoGallery', '
09-Aug-2016 13:58:27	 Instance Id:f406fc0d-cb87-ad08-4d77-93c2d81db747', '
09-Aug-2016 13:58:27	 Message: null is not an object (evaluating 'this.options.frameAspectRatio')', '', '
09-Aug-2016 13:58:27	 Stack:', 'init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:669:39
09-Aug-2016 13:58:27	init@[native code]
09-Aug-2016 13:58:27	http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2458:17
09-Aug-2016 13:58:27	forEach@[native code]
09-Aug-2016 13:58:27	init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2447:44
09-Aug-2016 13:58:27	init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2134:30
09-Aug-2016 13:58:27	http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:68206:34
09-Aug-2016 13:58:27	callFn@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4471:25
09-Aug-2016 13:58:27	run@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4464:13
09-Aug-2016 13:58:27	next@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4810:13
09-Aug-2016 13:58:27	http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4832:9
09-Aug-2016 13:58:27	timeslice@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:75:27'
09-Aug-2016 13:58:27	ERROR: 'Error on Module: PromoCard', '
09-Aug-2016 13:58:27	 Instance Id:7ab7a88d-9b9f-36ad-3172-9311e632b35d', '
09-Aug-2016 13:58:27	 Message: null is not an object (evaluating 'this.options.image')', '', '
09-Aug-2016 13:58:27	 Stack:', 'init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:1201:28
09-Aug-2016 13:58:27	init@[native code]
09-Aug-2016 13:58:27	http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2458:17
09-Aug-2016 13:58:27	forEach@[native code]
09-Aug-2016 13:58:27	init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2447:44
09-Aug-2016 13:58:27	init@http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:2134:30
09-Aug-2016 13:58:27	http://localhost:9876/absolute/tmp/9b454771dbfe973269fd6d83b579e9a5.browserify?45de4e5953fb5c4ee1c4bf798739a8b58e156602:68206:34
09-Aug-2016 13:58:27	callFn@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4471:25
09-Aug-2016 13:58:27	run@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4464:13
09-Aug-2016 13:58:27	next@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4810:13
09-Aug-2016 13:58:27	http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:4832:9
09-Aug-2016 13:58:27	timeslice@http://localhost:9876/base/node_modules/mocha/mocha.js?91557a9e8a222ad90c0392709844a7c448515b9d:75:27'
```

**Comment by asabaylus** [comment]
Issues in tests are unrelated, this is ready to ship

**Pull request merged**
